name: Go Test (with Testcontainers)

on:
  push:
    branches:
      - main
      - feature/**
  pull_request:
    branches:
      - main
      - feature/**

jobs:
  test:
    name: Run Go Tests in testcontainers module
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go environment
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Install dependencies
        run: go mod tidy
        working-directory: ./testcontainers


      - name: Run Go tests
        run: go test -v
        working-directory: ./testcontainers

